//
// Created by socce on 3/2/2022.
//

#ifndef OPERATINGSYSTEMSASSIGNMENT2_THREADHELPER_H
#define OPERATINGSYSTEMSASSIGNMENT2_THREADHELPER_H


class threadHelper {

};


#endif //OPERATINGSYSTEMSASSIGNMENT2_THREADHELPER_H
